# This workflow will ensure website features work perfectly
name: Checks

# Controls when the action will run
on:
  # Workflow runs every time when a commit is pushed to the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout repository for workflow to access
      - name: Checkout
        uses: actions/checkout@v3

      # Setup environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"
      - name: Install dependencies
        run: npm install

      # Run test (CI)
      - name: Run test
        run: npm test

      # Deploy (CD)
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "student-grade-system"
          heroku_email: "g00377198@atu.ie"
